spring.application.name=sentinelai

# ----------------------------------------
# PostgreSQL
# ----------------------------------------

spring.datasource.url=jdbc:postgresql://localhost:5433/sentinelai
spring.datasource.username=sentinelai
spring.datasource.password=sentinelai_dev

# ----------------------------------------
# JPA
# ----------------------------------------

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# ----------------------------------------
# Flyway
# ----------------------------------------

spring.flyway.enabled=true

# ----------------------------------------
# Actuator
# ----------------------------------------

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always