spring.application.name=sentinelai

# ----------------------------------------
# PostgreSQL
# ----------------------------------------

spring.datasource.url=jdbc:postgresql://localhost:5433/sentinelai
spring.datasource.username=sentinelai
spring.datasource.password=sentinelai_dev

# ----------------------------------------
# JPA
# ----------------------------------------

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# ----------------------------------------
# Flyway
# ----------------------------------------

spring.flyway.enabled=true

# ----------------------------------------
# Actuator
# ----------------------------------------

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ----------------------------------------
# Kafka
# ----------------------------------------

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties[spring.json.add.type.headers]=false

# ----------------------------------------
# Kafka Consumer
# ----------------------------------------

spring.kafka.consumer.group-id=sentinelai-telemetry-processor
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties[spring.json.value.default.type]=com.sentinelai.telemetry.event.logTelemetryEvent
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.sentinelai.telemetry.event
spring.kafka.consumer.properties[spring.json.use.type.headers]=false